#!/usr/bin/env bash

set -euo pipefail
cd "$(dirname "$0")/../.."
shopt -s extglob

script/bundle-linux --flatpak
archive_match="gram(-[a-zA-Z0-9]+)?-linux-$(uname -m)\.tar\.gz"
archive=$(ls "target/release" | grep -E ${archive_match})
channel=$(<crates/gram/RELEASE_CHANNEL)

export CHANNEL="$channel"
export ARCHIVE="$archive"
if [[ "$channel" == "dev" ]]; then
    export APP_ID="se.ziran.GramDev"
    export APP_NAME="Gram Devel"
    export BRANDING_LIGHT="#99c1f1"
    export BRANDING_DARK="#1a5fb4"
    export ICON_FILE="app-icon-dev"
elif [[ "$channel" == "stable" ]]; then
    export APP_ID="se.ziran.Gram"
    export APP_NAME="Gram"
    export BRANDING_LIGHT="#99c1f1"
    export BRANDING_DARK="#1a5fb4"
    export ICON_FILE="app-icon"
else
    echo "Invalid channel: '$channel'"
    exit
fi

envsubst < "crates/gram/resources/flatpak/manifest-template.json" > "$APP_ID.json"
flatpak-builder --user --install --force-clean build "$APP_ID.json"
flatpak build-bundle ~/.local/share/flatpak/repo "target/release/$APP_ID.flatpak" "$APP_ID"
echo "Created 'target/release/$APP_ID.flatpak'"
