#!/usr/bin/env bash

set -euxo pipefail

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <release_version>"
  exit 1
fi

mkdir -p snap/gui

export DO_STARTUP_NOTIFY="true"
export APP_NAME="Tehanu"
export APP_CLI="tehanu"
export APP_ICON="\${SNAP}/meta/gui/tehanu.png"
export APP_ARGS="%U"
envsubst < "crates/tehanu/resources/tehanu.desktop.in" > "snap/gui/tehanu.desktop"
cp "crates/tehanu/resources/app-icon.png" "snap/gui/tehanu.png"

RELEASE_VERSION="$1" envsubst < crates/tehanu/resources/snap/snapcraft.yaml.in > snap/snapcraft.yaml

# Clean seems to be needed to actually check that the snapcraft.yaml
# works.  For example, when a `stage-package` is removed, it will
# still remain on rebuild.
snapcraft clean

snapcraft
