name: Release test

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-test_[0-9]+"

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v6

      - name: get cargo
        run: cargo -V

      - uses: actions/cache@v5
        name: cache_deps split it up
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
          key: ${{ runner.os }}-deps0-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps0

      - uses: actions/cache@v5
        name: cache_deps because
        with:
          path: |
            ~/.cargo/bin/
          key: ${{ runner.os }}-deps1-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps1

      - uses: actions/cache@v5
        name: cache_deps github sucks
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
          key: ${{ runner.os }}-deps2-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps2

      - uses: actions/cache@v5
        name: cache_deps burma shave
        with:
          path: |
            ~/.cargo/git/db/
          key: ${{ runner.os }}-deps3-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps3

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Fix microslop # https://github.com/microsoft/python-environment-tools/issues/171
        shell: bash
        run: git config --global core.longpaths true

      - name: Build
        run: cargo build --verbose --release --package gram --package cli --target ${{ matrix.target }}

      - name: Build archive
        shell: bash
        run: |
          ls "target/${{ matrix.target }}/release"

      - name: Build archive
        shell: bash
        run: |

          binary_name="gram"
          dirname="$binary_name-${{ env.VERSION }}-${{ matrix.target }}"
          mkdir "$dirname"
          mv "target/${{ matrix.target }}/release/$binary_name.exe" "$dirname"
          mv "target/${{ matrix.target }}/release/cli.exe" "$dirname"

          7z a "$dirname.zip" "$dirname"
          echo "ASSET=$dirname.zip" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ASSET }}
